name: cpuccino_ui
description: Cpuccino UI Kit built for flutter
version: 0.0.0
author: cpuccino
homepage: https://github.com/cpuccino/cpuccino_ui
publish_to: none

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
